# Dependencies

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Files to Load
bar_data_to_load = "../Data/minwage.csv"

# Read minwage data and store into a Pandas DataFrame
min_wage_data = pd.read_csv(bar_data_to_load, encoding='cp1252')

In [3]:
# Review raw data

min_wage_data

,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.80,...,0.00000,0.00,0.00000,0.00,NaN
1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.80,2.1,2.10000,15.61,2.10000,15.61,NaN
2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.80,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91,(b)
3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.80,1.25/day(b),0.15625,1.16,0.15625,1.16,(b)
4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.80,1.65(b),1.65000,12.26,1.65000,12.26,(b)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,2020,Virginia,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25[c],7.25000,7.25,7.25000,7.25,[c]
2858,2020,Washington,13.50000,13.50,7.25,7.25,13.50,13.50,258.66,13.5,13.50000,13.50,13.50000,13.50,NaN
2859,2020,West Virginia,8.75000,8.75,7.25,7.25,8.75,8.75,258.66,8.75,8.75000,8.75,8.75000,8.75,NaN
2860,2020,Wisconsin,7.25000,7.25,7.25,7.25,7.25,7.25,258.66,7.25,7.25000,7.25,7.25000,7.25,NaN
2861,2020,Wyoming,5.15000,5.15,7.25,7.25,7.25,7.25,258.66,5.15,5.15000,5.15,5.15000,5.15,NaN

In [4]:
# Clean raw data by dropping columns

min_wage_data_drop = min_wage_data.drop(columns=['State.Minimum.Wage.2020.Dollars', 'Federal.Minimum.Wage.2020.Dollars',
                                                 'Effective.Minimum.Wage', 'CPI.Average', 'Department.Of.Labor.Uncleaned.Data',
                                                 'Department.Of.Labor.Cleaned.Low.Value', 'Department.Of.Labor.Cleaned.Low.Value.2020.Dollars',
                                                'Department.Of.Labor.Cleaned.High.Value', 'Department.Of.Labor.Cleaned.High.Value.2020.Dollars',
                                                'Footnote', 'Effective.Minimum.Wage.2020.Dollars'])
min_wage_data_drop

      Year          State  State.Minimum.Wage  Federal.Minimum.Wage
0     1968        Alabama             0.00000                  1.15
1     1968         Alaska             2.10000                  1.15
2     1968        Arizona             0.46800                  1.15
3     1968       Arkansas             0.15625                  1.15
4     1968     California             1.65000                  1.15
...    ...            ...                 ...                   ...
2857  2020       Virginia             7.25000                  7.25
2858  2020     Washington            13.50000                  7.25
2859  2020  West Virginia             8.75000                  7.25
2860  2020      Wisconsin             7.25000                  7.25
2861  2020        Wyoming             5.15000                  7.25

[2862 rows x 4 columns]

In [5]:
# Clean raw data to drop information prior to 1970

min_wage_data = min_wage_data_drop[(min_wage_data_drop['Year']>= 1970 )]
min_wage_data

      Year          State  State.Minimum.Wage  Federal.Minimum.Wage
108   1970        Alabama               0.000                  1.30
109   1970         Alaska               2.100                  1.30
110   1970        Arizona               0.468                  1.30
111   1970       Arkansas               1.100                  1.30
112   1970     California               1.650                  1.30
...    ...            ...                 ...                   ...
2857  2020       Virginia               7.250                  7.25
2858  2020     Washington              13.500                  7.25
2859  2020  West Virginia               8.750                  7.25
2860  2020      Wisconsin               7.250                  7.25
2861  2020        Wyoming               5.150                  7.25

[2754 rows x 4 columns]

In [6]:
# Create a DF for only the year and Federal min wage

fed_year_min_wage_data = min_wage_data.drop(columns=['State', 'State.Minimum.Wage'] )
fed_year_min_wage_data

      Year  Federal.Minimum.Wage
108   1970                  1.30
109   1970                  1.30
110   1970                  1.30
111   1970                  1.30
112   1970                  1.30
...    ...                   ...
2857  2020                  7.25
2858  2020                  7.25
2859  2020                  7.25
2860  2020                  7.25
2861  2020                  7.25

[2754 rows x 2 columns]

In [7]:
# Drop dulpicate years to only have a unique year matching the Federal min wage

CleanFedMinWage = fed_year_min_wage_data.drop_duplicates(subset=['Year'])
CleanFedMinWage

      Year  Federal.Minimum.Wage
108   1970                  1.30
162   1971                  1.30
216   1972                  1.60
270   1973                  1.60
324   1974                  1.60
378   1975                  1.60
432   1976                  2.20
486   1977                  2.20
540   1978                  2.20
594   1979                  2.90
648   1980                  3.10
702   1981                  3.35
756   1982                  3.35
810   1983                  3.35
864   1984                  3.35
918   1985                  3.35
972   1986                  3.35
1026  1987                  3.35
1080  1988                  3.35
1134  1989                  3.35
1188  1990                  3.35
1242  1991                  3.80
1296  1992                  4.25
1350  1993                  4.25
1404  1994                  4.25
1458  1995                  4.25
1512  1996                  4.25
1566  1997                  4.75
1620  1998                  5.15
1674  1999                  5.15
1728  2000                  5.15
1782  2001                  5.15
1836  2002                  5.15
1890  2003                  5.15
1944  2004                  5.15
1998  2005                  5.15
2052  2006                  5.15
2106  2007                  5.15
2160  2008                  5.85
2214  2009                  6.55
2268  2010                  7.25
2322  2011                  7.25
2376  2012                  7.25
2430  2013                  7.25
2484  2014                  7.25
2538  2015                  7.25
2592  2016                  7.25
2646  2017                  7.25
2700  2018                  7.25
2754  2019                  7.25
2808  2020                  7.25

In [8]:
# Rename columns to help support your python analysis

CleanFedMinWage1 = CleanFedMinWage.rename(columns={'Year': 'year'})
CleanFedMinWage1

      year  Federal.Minimum.Wage
108   1970                  1.30
162   1971                  1.30
216   1972                  1.60
270   1973                  1.60
324   1974                  1.60
378   1975                  1.60
432   1976                  2.20
486   1977                  2.20
540   1978                  2.20
594   1979                  2.90
648   1980                  3.10
702   1981                  3.35
756   1982                  3.35
810   1983                  3.35
864   1984                  3.35
918   1985                  3.35
972   1986                  3.35
1026  1987                  3.35
1080  1988                  3.35
1134  1989                  3.35
1188  1990                  3.35
1242  1991                  3.80
1296  1992                  4.25
1350  1993                  4.25
1404  1994                  4.25
1458  1995                  4.25
1512  1996                  4.25
1566  1997                  4.75
1620  1998                  5.15
1674  1999                  5.15
1728  2000                  5.15
1782  2001                  5.15
1836  2002                  5.15
1890  2003                  5.15
1944  2004                  5.15
1998  2005                  5.15
2052  2006                  5.15
2106  2007                  5.15
2160  2008                  5.85
2214  2009                  6.55
2268  2010                  7.25
2322  2011                  7.25
2376  2012                  7.25
2430  2013                  7.25
2484  2014                  7.25
2538  2015                  7.25
2592  2016                  7.25
2646  2017                  7.25
2700  2018                  7.25
2754  2019                  7.25
2808  2020                  7.25

In [9]:
# Rename columns to help support your python analysis
CleanFedMinWage2 = CleanFedMinWage1.rename(columns={'Federal.Minimum.Wage': 'federalminimumwage'})
CleanFedMinWage2

      year  federalminimumwage
108   1970                1.30
162   1971                1.30
216   1972                1.60
270   1973                1.60
324   1974                1.60
378   1975                1.60
432   1976                2.20
486   1977                2.20
540   1978                2.20
594   1979                2.90
648   1980                3.10
702   1981                3.35
756   1982                3.35
810   1983                3.35
864   1984                3.35
918   1985                3.35
972   1986                3.35
1026  1987                3.35
1080  1988                3.35
1134  1989                3.35
1188  1990                3.35
1242  1991                3.80
1296  1992                4.25
1350  1993                4.25
1404  1994                4.25
1458  1995                4.25
1512  1996                4.25
1566  1997                4.75
1620  1998                5.15
1674  1999                5.15
1728  2000                5.15
1782  2001                5.15
1836  2002                5.15
1890  2003                5.15
1944  2004                5.15
1998  2005                5.15
2052  2006                5.15
2106  2007                5.15
2160  2008                5.85
2214  2009                6.55
2268  2010                7.25
2322  2011                7.25
2376  2012                7.25
2430  2013                7.25
2484  2014                7.25
2538  2015                7.25
2592  2016                7.25
2646  2017                7.25
2700  2018                7.25
2754  2019                7.25
2808  2020                7.25

In [10]:
CleanFedMinWage2.dtypes

year                    int64
federalminimumwage    float64
dtype: object

In [16]:
# Create Unique Years and states to help create a new DataFrame

years = min_wage_data.Year.unique()
states = min_wage_data.State.unique()
print(years)
print(states)

[1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020]
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'U.S. Virgin Islands'
 'Utah' 'Vermont' 'Virginia' 'Washington' 'West Virginia' 'Wisconsin'
 'Wyoming']

In [17]:
# Continue to muniplate states

rearrage_min_wage_data = pd.DataFrame(states, columns = ['State'])
rearrage_min_wage_data.head()

        State
0     Alabama
1      Alaska
2     Arizona
3    Arkansas
4  California

In [18]:
#Rename your second dataframe

min_wage = min_wage_data[["Year", "State", "State.Minimum.Wage", 'Federal.Minimum.Wage' ]]
min_wage = min_wage.rename(columns={'Year': 'year', 'State': 'state', 'State.Minimum.Wage': 'stateminimumwage', 'Federal.Minimum.Wage': 'federalminimumwage'})
min_wage.head(10)

     year                 state  stateminimumwage  federalminimumwage
108  1970               Alabama             0.000                 1.3
109  1970                Alaska             2.100                 1.3
110  1970               Arizona             0.468                 1.3
111  1970              Arkansas             1.100                 1.3
112  1970            California             1.650                 1.3
113  1970              Colorado             1.000                 1.3
114  1970           Connecticut             1.600                 1.3
115  1970              Delaware             1.250                 1.3
116  1970  District of Columbia             1.600                 1.3
117  1970               Florida             0.000                 1.3

In [19]:
# Review list of columns

cols = list(min_wage.columns.values)
cols

['year', 'state', 'stateminimumwage', 'federalminimumwage']

In [20]:
#rearrange columns

min_wage = min_wage[['year', 'state', 'federalminimumwage', 'stateminimumwage']]
min_wage

      year          state  federalminimumwage  stateminimumwage
108   1970        Alabama                1.30             0.000
109   1970         Alaska                1.30             2.100
110   1970        Arizona                1.30             0.468
111   1970       Arkansas                1.30             1.100
112   1970     California                1.30             1.650
...    ...            ...                 ...               ...
2857  2020       Virginia                7.25             7.250
2858  2020     Washington                7.25            13.500
2859  2020  West Virginia                7.25             8.750
2860  2020      Wisconsin                7.25             7.250
2861  2020        Wyoming                7.25             5.150

[2754 rows x 4 columns]

In [21]:
# Change your DataFrame to have years as columns and min wage for each state, year is shown

for year in years:
    new_min_wage = min_wage.loc[(min_wage.year == year)]
    list1 = new_min_wage['stateminimumwage'].tolist()
    rearrage_min_wage_data[year] = list1
rearrage_min_wage_data

,State,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Alabama,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Alaska,2.100,2.100,2.100,2.100,2.100,2.100,2.80,2.80,2.80,...,7.75,7.75,7.75,7.75,8.75,9.75,9.80,9.84,10.19,10.19
2,Arizona,0.468,0.468,0.468,0.468,0.468,0.468,0.00,0.00,0.00,...,7.35,7.65,7.80,7.90,8.05,8.05,10.00,10.50,12.00,12.00
3,Arkansas,1.100,1.100,1.200,1.200,1.200,1.200,1.90,1.90,1.90,...,6.25,6.25,6.25,6.25,7.50,8.00,8.50,8.50,9.25,10.00
4,California,1.650,1.650,1.650,1.650,1.650,1.650,2.00,2.00,2.00,...,8.00,8.00,8.00,9.00,9.00,10.00,10.00,11.00,12.00,13.00
5,Colorado,1.000,1.000,1.000,1.000,1.000,1.000,1.00,1.00,1.00,...,7.36,7.64,7.78,8.00,8.23,8.31,9.30,10.20,12.00,12.00
6,Connecticut,1.600,1.600,1.850,1.850,1.850,1.850,2.21,2.21,2.21,...,8.25,8.25,8.25,8.70,9.15,9.60,10.10,10.10,11.00,11.00
7,Delaware,1.250,1.250,1.600,1.600,1.600,1.600,2.00,2.00,2.00,...,7.25,7.25,7.25,7.75,8.25,8.25,8.25,8.25,9.25,9.25
8,District of Columbia,1.600,1.600,1.600,1.600,1.600,1.600,2.25,2.25,2.25,...,8.25,8.25,8.25,9.50,10.50,11.50,11.50,13.25,14.00,14.00
9,Florida,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.67,7.79,7.93,8.05,8.05,8.10,8.25,8.56,8.56
10,Georgia,0.000,0.000,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15
11,Guam,1.600,1.600,1.900,1.900,1.900,1.900,2.30,2.30,2.30,...,7.25,7.25,7.25,7.25,8.25,8.25,8.25,8.25,8.25,8.25
12,Hawaii,1.600,1.600,1.600,1.600,1.600,1.600,2.40,2.40,2.40,...,7.25,7.25,7.25,7.25,7.75,8.50,9.25,10.10,10.10,10.10
13,Idaho,1.250,1.250,1.400,1.400,1.400,1.400,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
14,Illinois,0.000,0.000,1.400,1.400,1.400,1.400,2.10,2.10,2.10,...,8.25,8.25,8.25,8.25,8.25,8.25,8.25,8.25,9.25,9.25
15,Indiana,1.250,1.250,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
16,Iowa,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
17,Kansas,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
18,Kentucky,0.650,0.650,0.650,0.650,0.650,0.650,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
19,Louisiana,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,Maine,1.600,1.600,1.400,1.400,1.400,1.400,2.30,2.30,2.30,...,7.50,7.50,7.50,7.50,7.50,7.50,9.00,10.00,12.00,12.00
21,Maryland,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,8.25,8.75,8.75,10.10,11.00,11.00
22,Massachusetts,1.600,1.600,1.750,1.750,1.750,1.750,2.10,2.10,2.10,...,8.00,8.00,8.00,8.00,9.00,10.00,11.00,11.00,12.75,12.75
23,Michigan,1.250,1.250,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.40,7.40,7.40,8.15,8.15,8.50,8.90,9.25,9.65,9.65
24,Minnesota,0.700,0.700,0.750,0.750,0.750,0.750,1.80,1.80,1.80,...,5.25,5.25,5.25,6.50,7.25,7.25,7.75,8.04,8.15,8.15
25,Mississippi,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26,Missouri,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.35,7.50,7.65,7.65,7.70,7.85,9.45,9.45
27,Montana,0.000,0.000,1.600,1.600,1.600,1.600,1.80,1.80,1.80,...,4.00,4.00,4.00,7.90,8.05,8.05,8.15,8.30,8.65,8.65
28,Nebraska,1.000,1.000,1.000,1.000,1.000,1.000,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,8.00,9.00,9.00,9.00,9.00,9.00
29,Nevada,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
30,New Hampshire,1.450,1.450,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
31,New Jersey,1.500,1.500,1.500,1.500,1.500,1.500,2.20,2.20,2.20,...,7.25,7.25,7.25,8.25,8.38,8.38,8.44,8.60,11.00,11.00
32,New Mexico,1.300,1.300,1.300,1.300,1.300,1.300,2.00,2.00,2.00,...,7.50,7.50,7.50,7.50,7.50,7.50,7.50,7.50,9.00,9.00
33,New York,1.600,1.600,1.850,1.850,1.850,1.850,2.30,2.30,2.30,...,7.25,7.25,7.25,8.00,8.75,9.00,9.70,10.40,11.80,11.80
34,North Carolina,1.250,1.250,1.450,1.450,1.450,1.450,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
35,North Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
36,Ohio,0.750,0.750,0.750,0.750,0.750,0.750,1.60,1.60,1.60,...,7.40,7.70,7.85,7.25,7.25,7.25,8.15,8.30,8.70,8.70
37,Oklahoma,1.000,1.000,1.400,1.400,1.400,1.400,1.80,1.80,1.80,...,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00
38,Oregon,1.250,1.250,1.250,1.250,1.250,1.250,2.30,2.30,2.30,...,8.50,8.80,8.95,9.10,9.25,9.75,9.75,10.75,11.25,11.25
39,Pennsylvania,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
40,Puerto Rico,0.430,0.430,0.650,0.650,0.650,0.650,0.76,0.76,0.76,...,0.00,0.00,0.00,5.08,5.08,5.08,5.08,5.08,5.08,5.08
41,Rhode Island,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,7.40,7.40,7.75,8.00,9.00,9.60,9.60,10.10,10.50,10.50
42,South Carolina,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
43,South Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.50,8.55,8.65,8.85,9.30,9.30
44,Tennessee,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
45,Texas,0.000,0.000,1.400,1.400,1.400,1.400,1.40,1.40,1.40,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
46,U.S. Virgin Islands,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,4.30,4.30,4.30,4.30,4.30,4.30,4.30,4.30,10.50,10.50
47,Utah,1.000,1.000,1.200,1.200,1.200,1.200,1.55,1.55,1.55,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
48,Vermont,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,8.15,8.46,8.60,8.73,9.15,9.60,10.00,10.50,10.96,10.96
49,Virginia,0.000,0.000,0.000,0.000,0.000,0.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
50,Washington,1.600,1.600,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,8.67,9.04,9.19,9.32,9.47,9.47,11.00,11.50,13.50,13.50
51,West Virginia,1.000,1.000,1.200,1.200,1.200,1.200,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.00,8.75,8.75,8.75,8.75,8.75
52,Wisconsin,1.300,1.300,1.450,1.450,1.450,1.450,2.10,2.10,2.10,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
53,Wyoming,1.300,1.300,1.500,1.500,1.500,1.500,1.60,1.60,1.60,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15

In [22]:
# Rename columns to help support your python analysis
rearrage_min_wage_data1 = rearrage_min_wage_data.rename(columns={'State': 'state'})
rearrage_min_wage_data1

,state,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Alabama,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Alaska,2.100,2.100,2.100,2.100,2.100,2.100,2.80,2.80,2.80,...,7.75,7.75,7.75,7.75,8.75,9.75,9.80,9.84,10.19,10.19
2,Arizona,0.468,0.468,0.468,0.468,0.468,0.468,0.00,0.00,0.00,...,7.35,7.65,7.80,7.90,8.05,8.05,10.00,10.50,12.00,12.00
3,Arkansas,1.100,1.100,1.200,1.200,1.200,1.200,1.90,1.90,1.90,...,6.25,6.25,6.25,6.25,7.50,8.00,8.50,8.50,9.25,10.00
4,California,1.650,1.650,1.650,1.650,1.650,1.650,2.00,2.00,2.00,...,8.00,8.00,8.00,9.00,9.00,10.00,10.00,11.00,12.00,13.00
5,Colorado,1.000,1.000,1.000,1.000,1.000,1.000,1.00,1.00,1.00,...,7.36,7.64,7.78,8.00,8.23,8.31,9.30,10.20,12.00,12.00
6,Connecticut,1.600,1.600,1.850,1.850,1.850,1.850,2.21,2.21,2.21,...,8.25,8.25,8.25,8.70,9.15,9.60,10.10,10.10,11.00,11.00
7,Delaware,1.250,1.250,1.600,1.600,1.600,1.600,2.00,2.00,2.00,...,7.25,7.25,7.25,7.75,8.25,8.25,8.25,8.25,9.25,9.25
8,District of Columbia,1.600,1.600,1.600,1.600,1.600,1.600,2.25,2.25,2.25,...,8.25,8.25,8.25,9.50,10.50,11.50,11.50,13.25,14.00,14.00
9,Florida,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.67,7.79,7.93,8.05,8.05,8.10,8.25,8.56,8.56
10,Georgia,0.000,0.000,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15
11,Guam,1.600,1.600,1.900,1.900,1.900,1.900,2.30,2.30,2.30,...,7.25,7.25,7.25,7.25,8.25,8.25,8.25,8.25,8.25,8.25
12,Hawaii,1.600,1.600,1.600,1.600,1.600,1.600,2.40,2.40,2.40,...,7.25,7.25,7.25,7.25,7.75,8.50,9.25,10.10,10.10,10.10
13,Idaho,1.250,1.250,1.400,1.400,1.400,1.400,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
14,Illinois,0.000,0.000,1.400,1.400,1.400,1.400,2.10,2.10,2.10,...,8.25,8.25,8.25,8.25,8.25,8.25,8.25,8.25,9.25,9.25
15,Indiana,1.250,1.250,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
16,Iowa,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
17,Kansas,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
18,Kentucky,0.650,0.650,0.650,0.650,0.650,0.650,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
19,Louisiana,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,Maine,1.600,1.600,1.400,1.400,1.400,1.400,2.30,2.30,2.30,...,7.50,7.50,7.50,7.50,7.50,7.50,9.00,10.00,12.00,12.00
21,Maryland,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,8.25,8.75,8.75,10.10,11.00,11.00
22,Massachusetts,1.600,1.600,1.750,1.750,1.750,1.750,2.10,2.10,2.10,...,8.00,8.00,8.00,8.00,9.00,10.00,11.00,11.00,12.75,12.75
23,Michigan,1.250,1.250,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.40,7.40,7.40,8.15,8.15,8.50,8.90,9.25,9.65,9.65
24,Minnesota,0.700,0.700,0.750,0.750,0.750,0.750,1.80,1.80,1.80,...,5.25,5.25,5.25,6.50,7.25,7.25,7.75,8.04,8.15,8.15
25,Mississippi,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26,Missouri,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.35,7.50,7.65,7.65,7.70,7.85,9.45,9.45
27,Montana,0.000,0.000,1.600,1.600,1.600,1.600,1.80,1.80,1.80,...,4.00,4.00,4.00,7.90,8.05,8.05,8.15,8.30,8.65,8.65
28,Nebraska,1.000,1.000,1.000,1.000,1.000,1.000,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,8.00,9.00,9.00,9.00,9.00,9.00
29,Nevada,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
30,New Hampshire,1.450,1.450,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
31,New Jersey,1.500,1.500,1.500,1.500,1.500,1.500,2.20,2.20,2.20,...,7.25,7.25,7.25,8.25,8.38,8.38,8.44,8.60,11.00,11.00
32,New Mexico,1.300,1.300,1.300,1.300,1.300,1.300,2.00,2.00,2.00,...,7.50,7.50,7.50,7.50,7.50,7.50,7.50,7.50,9.00,9.00
33,New York,1.600,1.600,1.850,1.850,1.850,1.850,2.30,2.30,2.30,...,7.25,7.25,7.25,8.00,8.75,9.00,9.70,10.40,11.80,11.80
34,North Carolina,1.250,1.250,1.450,1.450,1.450,1.450,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
35,North Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
36,Ohio,0.750,0.750,0.750,0.750,0.750,0.750,1.60,1.60,1.60,...,7.40,7.70,7.85,7.25,7.25,7.25,8.15,8.30,8.70,8.70
37,Oklahoma,1.000,1.000,1.400,1.400,1.400,1.400,1.80,1.80,1.80,...,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00
38,Oregon,1.250,1.250,1.250,1.250,1.250,1.250,2.30,2.30,2.30,...,8.50,8.80,8.95,9.10,9.25,9.75,9.75,10.75,11.25,11.25
39,Pennsylvania,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
40,Puerto Rico,0.430,0.430,0.650,0.650,0.650,0.650,0.76,0.76,0.76,...,0.00,0.00,0.00,5.08,5.08,5.08,5.08,5.08,5.08,5.08
41,Rhode Island,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,7.40,7.40,7.75,8.00,9.00,9.60,9.60,10.10,10.50,10.50
42,South Carolina,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
43,South Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.50,8.55,8.65,8.85,9.30,9.30
44,Tennessee,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
45,Texas,0.000,0.000,1.400,1.400,1.400,1.400,1.40,1.40,1.40,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
46,U.S. Virgin Islands,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,4.30,4.30,4.30,4.30,4.30,4.30,4.30,4.30,10.50,10.50
47,Utah,1.000,1.000,1.200,1.200,1.200,1.200,1.55,1.55,1.55,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
48,Vermont,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,8.15,8.46,8.60,8.73,9.15,9.60,10.00,10.50,10.96,10.96
49,Virginia,0.000,0.000,0.000,0.000,0.000,0.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
50,Washington,1.600,1.600,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,8.67,9.04,9.19,9.32,9.47,9.47,11.00,11.50,13.50,13.50
51,West Virginia,1.000,1.000,1.200,1.200,1.200,1.200,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.00,8.75,8.75,8.75,8.75,8.75
52,Wisconsin,1.300,1.300,1.450,1.450,1.450,1.450,2.10,2.10,2.10,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
53,Wyoming,1.300,1.300,1.500,1.500,1.500,1.500,1.60,1.60,1.60,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15

In [23]:
# Change the name of the DataFrame

CleanMinWage = rearrage_min_wage_data1
CleanMinWage

,state,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Alabama,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Alaska,2.100,2.100,2.100,2.100,2.100,2.100,2.80,2.80,2.80,...,7.75,7.75,7.75,7.75,8.75,9.75,9.80,9.84,10.19,10.19
2,Arizona,0.468,0.468,0.468,0.468,0.468,0.468,0.00,0.00,0.00,...,7.35,7.65,7.80,7.90,8.05,8.05,10.00,10.50,12.00,12.00
3,Arkansas,1.100,1.100,1.200,1.200,1.200,1.200,1.90,1.90,1.90,...,6.25,6.25,6.25,6.25,7.50,8.00,8.50,8.50,9.25,10.00
4,California,1.650,1.650,1.650,1.650,1.650,1.650,2.00,2.00,2.00,...,8.00,8.00,8.00,9.00,9.00,10.00,10.00,11.00,12.00,13.00
5,Colorado,1.000,1.000,1.000,1.000,1.000,1.000,1.00,1.00,1.00,...,7.36,7.64,7.78,8.00,8.23,8.31,9.30,10.20,12.00,12.00
6,Connecticut,1.600,1.600,1.850,1.850,1.850,1.850,2.21,2.21,2.21,...,8.25,8.25,8.25,8.70,9.15,9.60,10.10,10.10,11.00,11.00
7,Delaware,1.250,1.250,1.600,1.600,1.600,1.600,2.00,2.00,2.00,...,7.25,7.25,7.25,7.75,8.25,8.25,8.25,8.25,9.25,9.25
8,District of Columbia,1.600,1.600,1.600,1.600,1.600,1.600,2.25,2.25,2.25,...,8.25,8.25,8.25,9.50,10.50,11.50,11.50,13.25,14.00,14.00
9,Florida,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.67,7.79,7.93,8.05,8.05,8.10,8.25,8.56,8.56
10,Georgia,0.000,0.000,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15
11,Guam,1.600,1.600,1.900,1.900,1.900,1.900,2.30,2.30,2.30,...,7.25,7.25,7.25,7.25,8.25,8.25,8.25,8.25,8.25,8.25
12,Hawaii,1.600,1.600,1.600,1.600,1.600,1.600,2.40,2.40,2.40,...,7.25,7.25,7.25,7.25,7.75,8.50,9.25,10.10,10.10,10.10
13,Idaho,1.250,1.250,1.400,1.400,1.400,1.400,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
14,Illinois,0.000,0.000,1.400,1.400,1.400,1.400,2.10,2.10,2.10,...,8.25,8.25,8.25,8.25,8.25,8.25,8.25,8.25,9.25,9.25
15,Indiana,1.250,1.250,1.250,1.250,1.250,1.250,1.25,1.25,1.25,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
16,Iowa,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
17,Kansas,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
18,Kentucky,0.650,0.650,0.650,0.650,0.650,0.650,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
19,Louisiana,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
20,Maine,1.600,1.600,1.400,1.400,1.400,1.400,2.30,2.30,2.30,...,7.50,7.50,7.50,7.50,7.50,7.50,9.00,10.00,12.00,12.00
21,Maryland,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,8.25,8.75,8.75,10.10,11.00,11.00
22,Massachusetts,1.600,1.600,1.750,1.750,1.750,1.750,2.10,2.10,2.10,...,8.00,8.00,8.00,8.00,9.00,10.00,11.00,11.00,12.75,12.75
23,Michigan,1.250,1.250,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.40,7.40,7.40,8.15,8.15,8.50,8.90,9.25,9.65,9.65
24,Minnesota,0.700,0.700,0.750,0.750,0.750,0.750,1.80,1.80,1.80,...,5.25,5.25,5.25,6.50,7.25,7.25,7.75,8.04,8.15,8.15
25,Mississippi,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26,Missouri,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,7.25,7.25,7.35,7.50,7.65,7.65,7.70,7.85,9.45,9.45
27,Montana,0.000,0.000,1.600,1.600,1.600,1.600,1.80,1.80,1.80,...,4.00,4.00,4.00,7.90,8.05,8.05,8.15,8.30,8.65,8.65
28,Nebraska,1.000,1.000,1.000,1.000,1.000,1.000,1.60,1.60,1.60,...,7.25,7.25,7.25,7.25,8.00,9.00,9.00,9.00,9.00,9.00
29,Nevada,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
30,New Hampshire,1.450,1.450,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
31,New Jersey,1.500,1.500,1.500,1.500,1.500,1.500,2.20,2.20,2.20,...,7.25,7.25,7.25,8.25,8.38,8.38,8.44,8.60,11.00,11.00
32,New Mexico,1.300,1.300,1.300,1.300,1.300,1.300,2.00,2.00,2.00,...,7.50,7.50,7.50,7.50,7.50,7.50,7.50,7.50,9.00,9.00
33,New York,1.600,1.600,1.850,1.850,1.850,1.850,2.30,2.30,2.30,...,7.25,7.25,7.25,8.00,8.75,9.00,9.70,10.40,11.80,11.80
34,North Carolina,1.250,1.250,1.450,1.450,1.450,1.450,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
35,North Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
36,Ohio,0.750,0.750,0.750,0.750,0.750,0.750,1.60,1.60,1.60,...,7.40,7.70,7.85,7.25,7.25,7.25,8.15,8.30,8.70,8.70
37,Oklahoma,1.000,1.000,1.400,1.400,1.400,1.400,1.80,1.80,1.80,...,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00
38,Oregon,1.250,1.250,1.250,1.250,1.250,1.250,2.30,2.30,2.30,...,8.50,8.80,8.95,9.10,9.25,9.75,9.75,10.75,11.25,11.25
39,Pennsylvania,1.300,1.300,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
40,Puerto Rico,0.430,0.430,0.650,0.650,0.650,0.650,0.76,0.76,0.76,...,0.00,0.00,0.00,5.08,5.08,5.08,5.08,5.08,5.08,5.08
41,Rhode Island,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,7.40,7.40,7.75,8.00,9.00,9.60,9.60,10.10,10.50,10.50
42,South Carolina,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
43,South Dakota,1.000,1.000,1.000,1.000,1.000,1.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.50,8.55,8.65,8.85,9.30,9.30
44,Tennessee,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
45,Texas,0.000,0.000,1.400,1.400,1.400,1.400,1.40,1.40,1.40,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
46,U.S. Virgin Islands,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00,0.00,...,4.30,4.30,4.30,4.30,4.30,4.30,4.30,4.30,10.50,10.50
47,Utah,1.000,1.000,1.200,1.200,1.200,1.200,1.55,1.55,1.55,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
48,Vermont,1.600,1.600,1.600,1.600,1.600,1.600,2.30,2.30,2.30,...,8.15,8.46,8.60,8.73,9.15,9.60,10.00,10.50,10.96,10.96
49,Virginia,0.000,0.000,0.000,0.000,0.000,0.000,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
50,Washington,1.600,1.600,1.600,1.600,1.600,1.600,2.20,2.20,2.20,...,8.67,9.04,9.19,9.32,9.47,9.47,11.00,11.50,13.50,13.50
51,West Virginia,1.000,1.000,1.200,1.200,1.200,1.200,2.00,2.00,2.00,...,7.25,7.25,7.25,7.25,8.00,8.75,8.75,8.75,8.75,8.75
52,Wisconsin,1.300,1.300,1.450,1.450,1.450,1.450,2.10,2.10,2.10,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25
53,Wyoming,1.300,1.300,1.500,1.500,1.500,1.500,1.60,1.60,1.60,...,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15,5.15

In [24]:
# Convert Fed Min Wage to a CSV

CleanFedMinWage.to_csv("../Data/FedMinWageByYear.csv", index=False)

In [25]:
# Convert States Min Wage to a CSV

CleanMinWage.to_csv("../Data/MinWageByState.csv", index=False)

In [26]:
# Import to SQL

from sqlalchemy import create_engine

In [27]:
# Connect to your SQL

rds_connection_string = "postgres:postgres@localhost:5432/USMinWage_DB"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [28]:
# Check for any existing tables

engine.table_names()

['minwagebystate', 'fedminwagebyyear']

In [30]:
# Use pandas to load csv converted DataFrame into database

CleanFedMinWage2.to_sql(name='fedminwagebyyear', con=engine, if_exists='append', index=False)

In [31]:
# Use pandas to load csv converted DataFrame into database

CleanMinWage.to_sql(name='minwagebystate', con=engine, if_exists='append', index=False)

In [33]:
# Confirm data has been added by querying your tables

pd.read_sql_query('select * from fedminwagebyyear', con=engine).head()

   year  federalminimumwage
0  1970                 1.3
1  1971                 1.3
2  1972                 1.6
3  1973                 1.6
4  1974                 1.6

In [34]:
# Confirm data has been added by querying your tables

pd.read_sql_query('select * from minwagebystate', con=engine).head()

,state,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Alabama,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00
1,Alaska,2.100,2.100,2.100,2.100,2.100,2.100,2.8,2.8,2.8,...,7.75,7.75,7.75,7.75,8.75,9.75,9.8,9.84,10.19,10.19
2,Arizona,0.468,0.468,0.468,0.468,0.468,0.468,0.0,0.0,0.0,...,7.35,7.65,7.80,7.90,8.05,8.05,10.0,10.50,12.00,12.00
3,Arkansas,1.100,1.100,1.200,1.200,1.200,1.200,1.9,1.9,1.9,...,6.25,6.25,6.25,6.25,7.50,8.00,8.5,8.50,9.25,10.00
4,California,1.650,1.650,1.650,1.650,1.650,1.650,2.0,2.0,2.0,...,8.00,8.00,8.00,9.00,9.00,10.00,10.0,11.00,12.00,13.00